name: Run Tests

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    
      # 1️⃣ Checkout الرمز
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ تثبيت Node.js (الإصدار 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3️⃣ تثبيت التبعيات (npm ci)
      - name: Install dependencies
        run: npm ci

      # 4️⃣ تشغيل الاختبارات
      - name: Run tests
        run: npm test
